name: Merged PR to main branch

on:
  pull_request:
    types:
      - closed
jobs:
  release:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: debug pr
        run: echo ${{toJson(github.event.pull_request)}}
      - name: Run action
        uses: amiiit/merge-bump-release@v0.1.2
        with:
          foo: 'hello'